import { Geist, Geist_Mono, Open_Sans } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";
import PersonalizationProvider from "./personalize";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  variable: "--font-opensans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

const cib = localFont({
  src: [
    {
      path: '../public/fonts/CIBFontSansBold.woff2',
      weight: '800'
    }
  ],
  variable: '--font-cib'
})

export const metadata = {
  title: "Bancolombia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${openSans.variable} ${cib.variable} antialiased`}
      >
        <PersonalizationProvider>{children}</PersonalizationProvider>
      </body>
    </html>
  );
}
